import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import PokeCard from "../hooks/card";
import useGetRandomPokemon from "../hooks/getRandomPokemon";
import { useEffect } from "react";
export default function Home() {
  // random -> array of 10 poke objects
  // loading will be false til promise resolves
  // fetchData calls the function
  const { random, loading, fetchData } = useGetRandomPokemon();
  //think this is why page running twice, that or fast refresh with next
  // normally would investigate but limited time remaiing
  useEffect(() => {
    if (random.length === 0 && loading) {
      fetchData();
    }
  }, [loading, random]);

  return (
    <div>
      <Head>
        <title>Pokédex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Pokédex!</h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>
        <div className={styles.grid}>
          <div>
            {!loading &&
              random.map((v, id) => {
                return <a key={id}>{PokeCard(v)}</a>;
              })}
          </div>
        </div>
      </main>
    </div>
  );
}
